shared:
  # applicatoins
  apps: &excluded_apps
    # x11
    - Gnome-terminal
    - Emacs
    - Code
    # wayland
    - code
    - gnome-terminal-server
  # keymaps
  emacs_keymap_cursor: &emacs_keymap_cursor
    C-b: { with_mark: left }
    C-f: { with_mark: right }
    C-p: { with_mark: up }
    C-n: { with_mark: down }
  emacs_keymap_cursor_line: &emacs_keymap_cursor_line
    C-a: { with_mark: home }
    C-e: { with_mark: end }
  emacs_keymap_cursor_more: &emacs_keymap_cursor_more
    # Forward/Backward word
    M-b: { with_mark: C-left }
    M-f: { with_mark: C-right }
    # Page up/down
    M-v: { with_mark: pageup }
    C-v: { with_mark: pagedown }
#    # Beginning/End of file
#    M-Shift-comma: { with_mark: C-home }
#    M-Shift-dot: { with_mark: C-end }
#    # Newline
#    C-m: enter
#    C-j: enter  # disabled for SKK
#    C-o: [enter, left]
  emacs_keymap_editing: &emacs_keymap_editing
#    # Copy
#    C-w: [C-x, { set_mark: false }]
#    M-w: [C-c, { set_mark: false }]
    C-y: [C-v, { set_mark: false }]
      # Delete
    C-h: [backspace, {set_mark: false}]
    C-d: [delete, { set_mark: false }]
#    M-d: [C-delete, { set_mark: false }]
    # Kill line
    C-k: [Shift-end, C-c, backspace, { set_mark: false }]
#    # Kill word backward
#    Alt-backspace: [C-backspace, {set_mark: false}]
#    # set mark next word continuously.
#    C-M-space: [C-Shift-right, {set_mark: true}]
#    # Undo
#    C-slash: [C-z, { set_mark: false }]
#    C-Shift-ro: C-z
#    # Mark
#    C-space: { set_mark: true }
#    # Search
#    C-s: C-f
#    C-r: Shift-F3
#    M-Shift-5: C-h
#    # Cancel
#    C-g: [esc, { set_mark: false }]
#    C-x YYY
#    C-x:
#      remap:
#        # C-x h (select all)
#        h: [C-home, C-a, { set_mark: true }]
#        # C-x C-f (open)
#        C-f: C-o
#        # C-x C-s (save)
#        C-s: C-s
#        # C-x k (kill tab)
#        k: C-f4
#        # C-x C-c (exit)
#        C-c: C-q
#        # C-x u (undo)
#        u: [C-z, { set_mark: false }]

modmap:
  - name: basic
    remap:
      CapsLock: Control_L

      # SKK hack for Chrome
      #C-j: C-m

keymap:
  - name: default
    remap: *emacs_keymap_cursor
    application:
      not: *excluded_apps
  - name: not for development apps (1)
    application:
      not: *excluded_apps
    remap: *emacs_keymap_cursor_line
  - name: not for development apps (2)
    application:
      not: *excluded_apps
    remap: *emacs_keymap_cursor_more
  - name: not for development apps (3)
    application:
      not: *excluded_apps
    remap: *emacs_keymap_editing
