shared:
  # applicatoins
  less_mod_apps: &less_mod_apps
    # dev tools
    - Gnome-terminal
    - gnome-terminal-server
    - Xfce4-terminal
    - xfce4-terminal
    - Emacs
    - Code
    - code
    # graphic apps
    - Gimp
    - gimp
    - Krita
    # - blender

  # keymaps
  emacs_keymap_minimal: &emacs_keymap_minimal
    C-b: { with_mark: left }
    C-f: { with_mark: right }
    C-p: { with_mark: up }
    C-n: { with_mark: down }
  emacs_keymap_normal: &emacs_keymap_normal
    C-a: { with_mark: home }
    C-e: { with_mark: end }
    # Forward/Backward word
    M-b: { with_mark: C-left }
    M-f: { with_mark: C-right }
    # Page up/down
    M-v: { with_mark: pageup }
    C-v: { with_mark: pagedown }
#    # Copy
#    C-w: [C-x, { set_mark: false }]
#    M-w: [C-c, { set_mark: false }]
    C-y: [C-v, { set_mark: false }]
    # Delete
    C-h: [backspace, {set_mark: false}]
    C-d: [delete, { set_mark: false }]
    # Kill line
    C-k: [Shift-end, C-c, backspace, { set_mark: false }]

#####
# main keymap & modmaps
#####

modmap:
  - name: basic
    remap:
      CapsLock: Control_L
      # SKK hack for Chrome
      #C-j: C-m

keymap:
  - name: minimal Emacs-like key bindings
    remap: *emacs_keymap_minimal

  - name: Emacs-like key bindings
    remap: *emacs_keymap_normal
    application:
      not: *less_mod_apps
