shared:
  dev_apps: &dev_apps
    - Gnome-terminal
    - gnome-terminal-server
    - Xfce4-terminal
    - xfce4-terminal
    - Emacs
    - Code
    - code

  emacs_keymap: &emacs_keymap
    C-b: { with_mark: left }
    C-f: { with_mark: right }
    C-p: { with_mark: up }
    C-n: { with_mark: down }
    C-a: { with_mark: home }
    C-e: { with_mark: end }
    # Forward/Backward word
    M-b: { with_mark: C-left }
    M-f: { with_mark: C-right }
    # Page up/down
    M-v: { with_mark: pageup }
    C-v: { with_mark: pagedown }
#    # Copy
#    C-w: [C-x, { set_mark: false }]
#    M-w: [C-c, { set_mark: false }]
    C-y: [C-v, { set_mark: false }]
    # Delete
    C-h: [backspace, {set_mark: false}]
    C-d: [delete, { set_mark: false }]
    # Kill line
    C-k: [Shift-end, C-c, backspace, { set_mark: false }]
    # mark
    Esc: { set_mark: false }
    C-g: { set_mark: false }
    C-space: { set_mark: true }

  mode_switch_keymap: &mode_switch_keymap
    C-S-Enter: { set_mode: Emacs }
    C-S-A-Enter: { set_mode: Off }

modmap:
  - name: basic
    remap:
      CapsLock: Control_L
      # SKK hack for Chrome
      #C-j: C-m

keymap:
  - name: Emacs-like key bindings
    remap: *emacs_keymap
    mode: [Emacs]
    application:
      not: *dev_apps
  - name: mode switching
    remap: *mode_switch_keymap
    mode: [Off, Emacs]

default_mode: Emacs
