#!/usr/bin/env bash

OPT=$HOME/opt

PATH=$PATH:$HOME/bin
PATH=$PATH:$HOME/.local/bin
PATH=$PATH:$HOME/apps/bin
PATH=$PATH:$OPT/bin

export EDITOR=lem
export LC_COLLATE="en_US.UTF-8"
export TERM=xterm-256color

# Common Lisp
PATH=$PATH:$HOME/.roswell/bin
PATH=$PATH:$HOME/.qlot/bin

# asdf

PATH="${ASDF_DATA_DIR:-$HOME/.asdf}/shims:$PATH"

# android studio

export ANDROID_HOME=$HOME/data.ssd/_android-studio/sdk
PATH=$PATH:$ANDROID_HOME/platform-tools
PATH=$PATH:$ANDROID_HOME/emulator
export ANDROID_NDK=$ANDROID_HOME/ndk/current

if [ "$(uname -o)" = "GNU/Linux" ]; then
  source ~/.bash_profile.linux
elif [ "$(uname -o)" = "Darwin" ]; then
  source ~/.bash_profile.mac
fi

export PATH

test -r "$HOME/.bashrc" && source "$HOME/.bashrc"
